// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<any>>;
export const modules: ModuleMap = {
  "./components/mockups/accordion.tsx": async () => { const mod = await import("../components/mockups/accordion.tsx"); return mod.default ?? mod; }
};
