import { mkdirSync, writeFileSync } from "fs";
import path from "path";
import glob from "fast-glob";
import chokidar from "chokidar";
import type { FSWatcher } from "chokidar";
import type { Plugin } from "vite";

const MOCKUPS_DIR = "src/components/mockups";
const GENERATED_MODULE = "src/.generated/mockup-components.ts";

interface DiscoveredComponent {
  globKey: string;
  importPath: string;
}

export function mockupPreviewPlugin(): Plugin {
  let root = "";
  let currentSource = "";
  let watcher: FSWatcher | null = null;

  function getMockupsAbsDir(): string {
    return path.join(root, MOCKUPS_DIR);
  }

  function getGeneratedModuleAbsPath(): string {
    return path.join(root, GENERATED_MODULE);
  }


  async function discoverComponents(): Promise<Array<DiscoveredComponent>> {
    const files = await glob(`${MOCKUPS_DIR}/**/*.tsx`, { cwd: root });

    return files.map((f) => ({
      globKey: "./" + f.slice("src/".length),
      importPath: path.posix.relative("src/.generated", f),
    }));
  }

  function generateSource(components: Array<DiscoveredComponent>): string {
    const entries = components
      .map(
        (c) =>
          `  ${JSON.stringify(c.globKey)}: () => import(${JSON.stringify(
            c.importPath
          )})`
      )
      .join(",\n");

    return [
      "// This file is auto-generated by mockupPreviewPlugin.ts.",
      "type ModuleMap = Record<string, () => Promise<any>>;", // any عشان TS يقبل
      "export const modules: ModuleMap = {",
      entries,
      "};",
      "",
    ].join("\n");
  }

  async function refresh(): Promise<void> {
    const components = await discoverComponents();
    const newSource = generateSource(components);
    if (newSource !== currentSource) {
      currentSource = newSource;
      const generatedModuleAbsPath = getGeneratedModuleAbsPath();
      mkdirSync(path.dirname(generatedModuleAbsPath), { recursive: true });
      writeFileSync(generatedModuleAbsPath, currentSource);
      console.log("[mockupPreview] Discovered components:", components.map(c => c.globKey));
    }
  }

  return {
    name: "mockup-preview",
    enforce: "pre",
    configResolved(config) {
      root = config.root;
    },
    async buildStart() {
      await refresh();
    },
    async configureServer(viteServer) {
      await refresh();
      const mockupsAbsDir = getMockupsAbsDir();
      mkdirSync(mockupsAbsDir, { recursive: true });

      watcher = chokidar.watch(mockupsAbsDir, { ignoreInitial: true });

      watcher.on("add", () => refresh());
      watcher.on("unlink", () => refresh());

      viteServer.middlewares.use((_req, res, next) => {
        const originalEnd = res.end.bind(res);
        res.end = ((...args: Parameters<typeof originalEnd>) => {
          void refresh();
          return originalEnd(...args);
        }) as typeof res.end;
        next();
      });
    },
    async closeWatcher() {
      if (watcher) await watcher.close();
    },
  };
}