/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PathFinder AI API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all conversations
 */
export const ListOpenaiConversationsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  createdAt: zod.date(),
});
export const ListOpenaiConversationsResponse = zod.array(
  ListOpenaiConversationsResponseItem,
);

/**
 * @summary Create a new conversation
 */
export const CreateOpenaiConversationBody = zod.object({
  title: zod.string(),
});

/**
 * @summary Get conversation with messages
 */
export const GetOpenaiConversationParams = zod.object({
  id: zod.coerce.number(),
});

export const GetOpenaiConversationResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  createdAt: zod.date(),
  messages: zod.array(
    zod.object({
      id: zod.number(),
      conversationId: zod.number(),
      role: zod.string(),
      content: zod.string(),
      createdAt: zod.date(),
    }),
  ),
});

/**
 * @summary Delete a conversation
 */
export const DeleteOpenaiConversationParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List messages in a conversation
 */
export const ListOpenaiMessagesParams = zod.object({
  id: zod.coerce.number(),
});

export const ListOpenaiMessagesResponseItem = zod.object({
  id: zod.number(),
  conversationId: zod.number(),
  role: zod.string(),
  content: zod.string(),
  createdAt: zod.date(),
});
export const ListOpenaiMessagesResponse = zod.array(
  ListOpenaiMessagesResponseItem,
);

/**
 * @summary Send a text message and receive a streaming text response
 */
export const SendOpenaiMessageParams = zod.object({
  id: zod.coerce.number(),
});

export const SendOpenaiMessageBody = zod.object({
  content: zod.string(),
});

/**
 * @summary Generate a personalized career roadmap
 */
export const GenerateCareerRoadmapBody = zod.object({
  careerInterest: zod.string(),
  educationLevel: zod.enum([
    "high_school",
    "university",
    "graduate",
    "self_learner",
  ]),
  skills: zod.string(),
  challenges: zod.string(),
  language: zod.enum(["en", "ar"]).optional(),
});

/**
 * @summary Compare two careers side by side
 */
export const CompareCareersBody = zod.object({
  career1: zod.string(),
  career2: zod.string(),
  language: zod.enum(["en", "ar"]).optional(),
});

export const CompareCareersResponse = zod.object({
  career1: zod.string(),
  career2: zod.string(),
  comparison: zod.object({
    skills: zod.object({
      career1: zod.array(zod.string()),
      career2: zod.array(zod.string()),
    }),
    salaryRange: zod.object({
      career1: zod.string(),
      career2: zod.string(),
    }),
    demand: zod.object({
      career1: zod.string(),
      career2: zod.string(),
    }),
    difficulty: zod.object({
      career1: zod.string(),
      career2: zod.string(),
    }),
    education: zod.object({
      career1: zod.string(),
      career2: zod.string(),
    }),
    verdict: zod.string(),
  }),
});

/**
 * @summary Generate AI resume
 */
export const GenerateResumeBody = zod.object({
  name: zod.string(),
  careerGoal: zod.string(),
  skills: zod.array(zod.string()),
  education: zod.string().optional(),
  experience: zod.string().optional(),
  language: zod.enum(["en", "ar"]).optional(),
});

export const GenerateResumeResponse = zod.object({
  resume: zod.string(),
  sections: zod.object({
    summary: zod.string(),
    skills: zod.string(),
    education: zod.string().optional(),
    experience: zod.string().optional(),
    projects: zod.string().optional(),
  }),
});

/**
 * @summary List all saved roadmaps
 */
export const ListSavedRoadmapsResponseItem = zod.object({
  id: zod.number(),
  careerTitle: zod.string(),
  roadmapData: zod.string(),
  completedSteps: zod.array(zod.number()),
  createdAt: zod.date(),
});
export const ListSavedRoadmapsResponse = zod.array(
  ListSavedRoadmapsResponseItem,
);

/**
 * @summary Save a career roadmap
 */
export const SaveRoadmapBody = zod.object({
  careerTitle: zod.string(),
  roadmapData: zod.string(),
});

/**
 * @summary Get a saved roadmap by ID
 */
export const GetSavedRoadmapParams = zod.object({
  id: zod.coerce.number(),
});

export const GetSavedRoadmapResponse = zod.object({
  id: zod.number(),
  careerTitle: zod.string(),
  roadmapData: zod.string(),
  completedSteps: zod.array(zod.number()),
  createdAt: zod.date(),
});

/**
 * @summary Delete a saved roadmap
 */
export const DeleteSavedRoadmapParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary Update progress steps for a roadmap
 */
export const UpdateRoadmapProgressParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateRoadmapProgressBody = zod.object({
  completedSteps: zod.array(zod.number()),
});

export const UpdateRoadmapProgressResponse = zod.object({
  id: zod.number(),
  careerTitle: zod.string(),
  roadmapData: zod.string(),
  completedSteps: zod.array(zod.number()),
  createdAt: zod.date(),
});
